import api from "./api";

/**
 * Products Service
 *
 * Wraps the /products endpoints. All list/detail responses include nested
 * { brand, category, branch } objects — no second fetch needed on the list page.
 *
 * Mutation endpoints (create, update, deactivate, reactivate) will 403 for
 * non-admin roles. The frontend disables buttons via usePermissions, but the
 * backend is the source of truth.
 */

/**
 * List products with optional filters.
 *
 * All filters are AND-combined server-side. Omitting a filter means "any".
 *
 * @param {Object} [filters]
 * @param {boolean} [filters.includeInactive] - Include deactivated products
 * @param {string}  [filters.brandId]         - Filter by brand UUID
 * @param {string}  [filters.categoryId]      - Filter by category UUID
 * @param {string}  [filters.branchId]        - Filter by branch UUID
 * @param {string}  [filters.productType]     - PHONE | ACCESSORY | WATCH | SPEAKER
 * @returns {Promise<Array>} Products with nested brand/category/branch
 */
export const listProducts = async (filters = {}) => {
  // Strip undefined/null/empty-string values so axios doesn't send them
  // as `?brandId=` (which some backends interpret as an empty filter).
  const params = Object.fromEntries(
    Object.entries(filters).filter(
      ([, v]) => v !== undefined && v !== null && v !== "",
    ),
  );

  const response = await api.get("/products", {
    params: Object.keys(params).length ? params : undefined,
  });
  return response.data;
};

/**
 * Get a single product by ID (with nested relations).
 *
 * @param {string} id - Product UUID
 * @returns {Promise<Object>} Product with nested brand/category/branch
 */
export const getProduct = async (id) => {
  const response = await api.get(`/products/${id}`);
  return response.data;
};

/**
 * Look up a product by exact barcode string.
 *
 * Used by the POS terminal scanner and the barcode-print flow. Backend
 * matches on both auto-generated SLP-XXXXXX and manufacturer barcodes.
 *
 * @param {string} barcode - Exact barcode string
 * @returns {Promise<Object>} Product with nested relations
 */
export const getProductByBarcode = async (barcode) => {
  const response = await api.get(
    `/products/by-barcode/${encodeURIComponent(barcode)}`,
  );
  return response.data;
};

/**
 * Create a new product (admin only).
 *
 * SKU is auto-generated by the backend — do NOT send `sku` in the payload.
 * Barcode is optional: if omitted, backend generates SLP-XXXXXX. If provided,
 * it must be unique across the catalog (409 otherwise).
 *
 * @param {Object} payload - CreateProductDto shape
 * @returns {Promise<Object>} Newly created product with nested relations
 */
export const createProduct = async (payload) => {
  const response = await api.post("/products", payload);
  return response.data;
};

/**
 * Update an existing product (admin only).
 *
 * SKU CAN be overridden on update (admin discretion). Must remain unique.
 * Any subset of fields may be sent — this is a PATCH, not a PUT.
 *
 * @param {string} id - Product UUID
 * @param {Object} payload - UpdateProductDto shape (partial)
 * @returns {Promise<Object>} Updated product with nested relations
 */
export const updateProduct = async (id, payload) => {
  const response = await api.patch(`/products/${id}`, payload);
  return response.data;
};

/**
 * Deactivate a product (soft delete, admin only).
 *
 * Sets is_active=false. Product is preserved for historical sales data.
 * Use `reactivateProduct` to restore.
 *
 * @param {string} id - Product UUID
 * @returns {Promise<Object>} Deactivated product
 */
export const deactivateProduct = async (id) => {
  const response = await api.delete(`/products/${id}`);
  return response.data;
};

/**
 * Reactivate a previously deactivated product (admin only).
 *
 * @param {string} id - Product UUID
 * @returns {Promise<Object>} Reactivated product
 */
export const reactivateProduct = async (id) => {
  const response = await api.post(`/products/${id}/reactivate`);
  return response.data;
};
